Repository joomlatools/joomlatools-framework, pull requests merged in 2018-08, with the labels that each got.

#173 Merge feature/172-search
  code/libraries/joomlatools/library/model/behavior/searchable.php
Labels: feature

#175 Proxy plugin events
  code/libraries/joomlatools/component/koowa/event/subscriber/application.php
  code/libraries/joomlatools/component/koowa/event/subscriber/unauthorized.php
  code/libraries/joomlatools/component/koowa/resources/config/bootstrapper.php
  code/libraries/joomlatools/library/event/publisher/abstract.php
  code/libraries/joomlatools/library/event/subscriber/abstract.php
  code/libraries/joomlatools/library/event/subscriber/factory.php
  code/libraries/joomlatools/library/event/subscriber/interface.php
  code/libraries/joomlatools/library/template/engine/factory.php
  code/libraries/joomlatools/plugin/koowa/subscriber.php
  code/plugins/system/joomlatools/joomlatools.php
Labels: feature, refactor

#177 Allow http transport to be used without wrapping Joomla or Koowa
  code/libraries/joomlatools/component/koowa/dispatcher/http.php
  code/libraries/joomlatools/component/koowa/dispatcher/response/transport/page.php
Labels: feature, refactor

#179 Merge feature/178-dbcharset
  code/libraries/joomlatools/component/koowa/database/adapter/mysqli.php
Labels: refactor
