Repository joomlatools/joomlatools-framework, pull requests merged in 2018-09, with the labels that each got.

#182 Allow behavior to specialise the is[Behavior] method
  code/libraries/joomlatools/library/behavior/abstract.php
Labels: feature

#183 Http Caching
  code/libraries/joomlatools/library/dispatcher/behavior/cacheable.php
  code/libraries/joomlatools/library/dispatcher/request/abstract.php
  code/libraries/joomlatools/library/dispatcher/request/interface.php
  code/libraries/joomlatools/library/dispatcher/response/transport/http.php
  code/libraries/joomlatools/library/dispatcher/response/transport/stream.php
  code/libraries/joomlatools/library/http/message/headers.php
  code/libraries/joomlatools/library/http/request/interface.php
  code/libraries/joomlatools/library/http/request/request.php
  code/libraries/joomlatools/library/http/response/interface.php
  code/libraries/joomlatools/library/http/response/response.php
Labels: feature

#180 Allow http transport to be used without wrapping Joomla or Koowa
  code/libraries/joomlatools/component/koowa/dispatcher/behavior/decoratable.php
  code/libraries/joomlatools/component/koowa/dispatcher/http.php
  code/libraries/joomlatools/component/koowa/dispatcher/response/transport/page.php
  code/libraries/joomlatools/component/koowa/template/filter/document.php
  code/libraries/joomlatools/component/koowa/template/filter/link.php
  code/libraries/joomlatools/component/koowa/template/filter/meta.php
  code/libraries/joomlatools/component/koowa/template/filter/script.php
  code/libraries/joomlatools/component/koowa/template/filter/style.php
  code/libraries/joomlatools/component/koowa/template/filter/title.php
  code/libraries/joomlatools/component/koowa/template/helper/behavior.php
  code/libraries/joomlatools/component/koowa/template/helper/ui.php
  code/libraries/joomlatools/component/koowa/views/html.php
  code/libraries/joomlatools/component/koowa/views/page/html.php
  code/libraries/joomlatools/library/dispatcher/abstract.php
  code/libraries/joomlatools/library/dispatcher/response/transport/abstract.php
  code/libraries/joomlatools/library/dispatcher/response/transport/http.php
Labels: refactor

#187 Use Transliterator in ascii filter
  code/libraries/joomlatools/component/koowa/filter/alias.php
  code/libraries/joomlatools/library/filter/ascii.php
Labels: refactor

#184 Allow decoration of JSON views
  code/libraries/joomlatools/library/dispatcher/response/abstract.php
  code/libraries/joomlatools/library/http/message/message.php
  code/libraries/joomlatools/library/object/config/json.php
  code/libraries/joomlatools/library/view/abstract.php
  code/libraries/joomlatools/library/view/interface.php
  code/libraries/joomlatools/library/view/json.php
  code/libraries/joomlatools/library/view/template.php
Labels: feature

#189 Dynamic module injection
  code/libraries/joomlatools/component/koowa/template/filter/module.php
Labels: feature

#191 Improve rendering flow
  code/libraries/joomlatools/component/koowa/dispatcher/behavior/decoratable.php
  code/libraries/joomlatools/component/koowa/dispatcher/http.php
  code/libraries/joomlatools/component/koowa/dispatcher/request/request.php
  code/libraries/joomlatools/library/controller/abstract.php
  code/libraries/joomlatools/library/controller/model.php
  code/libraries/joomlatools/library/controller/response/response.php
  code/libraries/joomlatools/library/controller/view.php
  code/libraries/joomlatools/library/dispatcher/abstract.php
  code/libraries/joomlatools/library/dispatcher/behavior/resettable.php
  code/libraries/joomlatools/library/dispatcher/http.php
  code/libraries/joomlatools/library/dispatcher/request/abstract.php
  code/libraries/joomlatools/library/dispatcher/response/transport/http.php
  code/libraries/joomlatools/library/http/message/message.php
  code/libraries/joomlatools/library/http/message/parameters.php
  code/libraries/joomlatools/library/http/response/response.php
  code/libraries/joomlatools/library/http/url/url.php
  code/libraries/joomlatools/library/object/config/format.php
  code/libraries/joomlatools/library/object/config/ini.php
  code/libraries/joomlatools/library/object/config/json.php
  code/libraries/joomlatools/library/object/config/php.php
  code/libraries/joomlatools/library/object/config/xml.php
  code/libraries/joomlatools/library/object/config/yaml.php
  code/libraries/joomlatools/library/view/abstract.php
  code/libraries/joomlatools/library/view/csv.php
  code/libraries/joomlatools/library/view/html.php
  code/libraries/joomlatools/library/view/json.php
  code/libraries/joomlatools/library/view/rss.php
Labels: feature

#195 Merge feature/194-dispatcher
  code/libraries/joomlatools/library/behavior/mixin/mixin.php
  code/libraries/joomlatools/library/dispatcher/behavior/permissible.php
Labels: refactor

#197 Merge feature/196-disposition
  code/libraries/joomlatools/library/dispatcher/response/transport/http.php
Labels: bug
