Repository joomlatools/joomlatools-framework, pull requests merged in 2018-11, with the labels that each got.

#209 Merge feature/208-jwt
  code/libraries/joomlatools/component/koowa/dispatcher/authenticator/jwt.php
Labels: bug

#211 Merge Feature/204 kui js
  code/libraries/joomlatools/component/koowa/template/helper/behavior.php
  code/libraries/joomlatools/library/resources/assets/js/build/admin.js
  code/libraries/joomlatools/library/resources/assets/js/build/kui-initialize.js
  code/libraries/joomlatools/library/resources/assets/js/build/modernizr.js
  code/libraries/joomlatools/library/resources/assets/js/min/admin.js
  code/libraries/joomlatools/library/resources/assets/js/min/kui-initialize.js
  code/libraries/joomlatools/library/resources/assets/js/min/modernizr.js
  code/libraries/joomlatools/library/template/helper/behavior.php
  code/libraries/joomlatools/library/template/helper/ui.php
Labels: refactor

#210 Merge feature/117-override
  code/libraries/joomlatools/component/koowa/template/locator/component.php
  code/libraries/joomlatools/component/koowa/template/locator/file.php
  code/libraries/joomlatools/component/koowa/template/locator/module.php
Labels: bug

#213 Merge Feature/212-delete
  code/libraries/joomlatools/library/dispatcher/abstract.php
  code/libraries/joomlatools/library/dispatcher/http.php
Labels: bug

#216 Consistently return base URL
  code/plugins/system/joomlatools/joomlatools.php
Labels: bug

#223 Platform compatibility for template overrides
  code/libraries/joomlatools/component/koowa/template/locator/component.php
  code/libraries/joomlatools/component/koowa/template/locator/file.php
  code/libraries/joomlatools/component/koowa/template/locator/module.php
Labels: bug

#222 An empty entity should be composite
  code/libraries/joomlatools/library/model/abstract.php
Labels: bug, feature

#225 Merge feature/224-formsubmit
  code/libraries/joomlatools/component/koowa/dispatcher/behavior/decoratable.php
  code/libraries/joomlatools/library/dispatcher/behavior/resettable.php
  code/libraries/joomlatools/library/http/request/interface.php
  code/libraries/joomlatools/library/http/request/request.php
Labels: refactor

#230 Merge Feature/229-js-prefix
  code/libraries/joomlatools/library/resources/assets/css/admin.css
  code/libraries/joomlatools/library/resources/assets/css/build/admin.css
  code/libraries/joomlatools/library/resources/assets/js/build/koowa.js
  code/libraries/joomlatools/library/resources/assets/js/min/koowa.js
  code/libraries/joomlatools/library/template/helper/behavior.php
  package-lock.json
Labels: refactor

#234 Merge Feature/232-yaml
  code/libraries/joomlatools/library/object/config/factory.php
Labels: refactor
