Repository joomlatools/joomlatools-framework, pull requests merged in 2019-01, with the labels that each got.

#242 Http caching fixes
  code/libraries/joomlatools/library/dispatcher/behavior/cacheable.php
  code/libraries/joomlatools/library/dispatcher/response/transport/http.php
  code/libraries/joomlatools/library/http/message/headers.php
  code/libraries/joomlatools/library/http/response/response.php
Labels: refactor

#244 #243: Always encode the file name for Internet Explorer
  code/libraries/joomlatools/library/dispatcher/response/transport/http.php
Labels: bug

#250 #245: Send method override with deletes
  code/libraries/joomlatools/library/resources/assets/js/build/koowa.js
  code/libraries/joomlatools/library/resources/assets/js/min/koowa.js
  package-lock.json
  package.json
Labels: bug

#249 Deep clone KTemplate
  code/libraries/joomlatools/library/template/template.php
Labels: bug

#252 Sanitise request base path
  code/libraries/joomlatools/library/dispatcher/request/abstract.php
Labels: refactor, security
