Repository joomlatools/joomlatools-framework, pull requests merged in 2019-10, with the labels that each got.

#312 Queries with multiple HAVING conditions fail
  code/libraries/joomlatools/library/database/query/select.php
Labels: bug

#315 Do not escape [ and ] in url's
  code/libraries/joomlatools/library/http/url/url.php
Labels: refactor

#317 Event subscribers cannot define priority
  code/libraries/joomlatools/component/koowa/event/subscriber/unauthorized.php
  code/libraries/joomlatools/library/event/publisher/exception.php
  code/libraries/joomlatools/library/event/subscriber/abstract.php
  code/libraries/joomlatools/library/event/subscriber/interface.php
  code/libraries/joomlatools/plugin/koowa/subscriber.php
  code/plugins/system/joomlatools/joomlatools.php
Labels: bug, prio:high
