Repository joomlatools/joomlatools-framework, pull requests merged in 2019-11, with the labels that each got.

#320 Update deprecated code
  code/libraries/joomlatools/component/koowa/template/helper/editor.php
Labels: refactor

#327 Allow to build a package without components
  build.xml
  code/plugins/system/joomlatools/script.php
Labels: feature, refactor

#324 Improve http support
  code/libraries/joomlatools/library/dispatcher/http.php
  code/libraries/joomlatools/library/dispatcher/response/transport/redirect.php
  code/libraries/joomlatools/library/http/request/interface.php
  code/libraries/joomlatools/library/http/request/request.php
Labels: refactor

#322 Implement http client
  code/libraries/joomlatools/library/http/client/client.php
  code/libraries/joomlatools/library/http/client/interface.php
  code/libraries/joomlatools/library/http/exception/error.php
  code/libraries/joomlatools/library/http/response/response.php
  code/libraries/joomlatools/library/object/config/factory.php
Labels: feature

#329 #328 - Add support for Update_time to database table schema
  code/libraries/joomlatools/library/database/adapter/mysqli.php
  code/libraries/joomlatools/library/database/schema/table.php
Labels: feature
