Repository joomlatools/joomlatools-framework, pull requests merged in 2020-04, with the labels that each got.

#361 Module filter params are not working
  code/libraries/joomlatools/component/koowa/template/filter/module.php
  code/libraries/joomlatools/library/template/engine/abstract.php
Labels: bug

#363 Add support for ORDER BY RAND()
  code/libraries/joomlatools/library/database/query/select.php
Labels: feature

#367 Disable Content-Length for non-downloadable requests
  code/libraries/joomlatools/library/dispatcher/response/transport/http.php
Labels: refactor
