Repository joomlatools/joomlatools-framework, pull requests merged in 2020-01, with the labels that each got.

#344 Metadata handling can lead to duplicates
  code/libraries/joomlatools/component/koowa/template/filter/meta.php
Labels: bug

#342 Add support for multi-dimensional data to CSV view
  code/libraries/joomlatools/library/view/csv.php
Labels: bug

#347 PHP 7.4 fixes
  code/libraries/joomlatools/library/http/message/headers.php
  code/libraries/joomlatools/library/http/message/parameters.php
  code/libraries/joomlatools/library/legacy.php
  code/libraries/joomlatools/library/object/queue.php
Labels: refactor

#348 Load languages with a fallback
  code/libraries/joomlatools/component/koowa/translator/translator.php
Labels: refactor

#354 Pretty print json
  code/libraries/joomlatools/library/object/config/json.php
Labels: refactor

#352 Support for Joomla module events
  code/plugins/system/joomlatools/joomlatools.php
Labels: feature
