Repository joomlatools/joomlatools-framework, pull requests merged in 2020-05, with the labels that each got.

#334 CSS overflow issue on demo
  code/libraries/joomlatools/component/koowa/resources/assets/css/admin.css
  code/libraries/joomlatools/library/resources/assets/css/admin.css
  code/libraries/joomlatools/library/resources/assets/css/build/admin.css
Labels: bug

#369 Add Alpine.js
  code/libraries/joomlatools/component/koowa/template/filter/script.php
  code/libraries/joomlatools/component/koowa/template/helper/behavior.php
  code/libraries/joomlatools/library/resources/assets/js/build/alpine-ie11.js
  code/libraries/joomlatools/library/resources/assets/js/build/alpine.js
  code/libraries/joomlatools/library/resources/assets/js/min/alpine-ie11.js
  code/libraries/joomlatools/library/resources/assets/js/min/alpine.js
  code/libraries/joomlatools/library/template/helper/behavior.php
Labels: feature

#365 Locking referrer bug
  code/libraries/joomlatools/library/controller/behavior/editable.php
Labels: bug

#335 Trash feature
  code/libraries/joomlatools/library/controller/behavior/trashable.php
  code/libraries/joomlatools/library/controller/toolbar/trashable.php
  code/libraries/joomlatools/library/model/behavior/trashable.php
Labels: feature

#375 Do not force a 301 redirect
  code/libraries/joomlatools/library/dispatcher/http.php
Labels: refactor

#373 Support relative datetime to set max age
  code/libraries/joomlatools/library/http/response/response.php
Labels: feature, refactor

#377 Use identifiers when registering config formats
  code/libraries/joomlatools/library/object/config/factory.php
Labels: bug, refactor

#382 Disable Content-Length for non-downloadable requests
  code/libraries/joomlatools/component/koowa/dispatcher/behavior/decoratable.php
Labels: refactor

#381 Issues merging identifiers in bootstrapper
  code/libraries/joomlatools/library/object/bootstrapper/bootstrapper.php
Labels: bug, prio:high

#384 Improve user object group and role handling
  code/libraries/joomlatools/component/koowa/database/table/groups.php
  code/libraries/joomlatools/component/koowa/database/table/roles.php
  code/libraries/joomlatools/component/koowa/event/subscriber/user.php
  code/libraries/joomlatools/component/koowa/user/default.php
  code/libraries/joomlatools/component/koowa/user/provider.php
  code/libraries/joomlatools/component/koowa/user/trait.php
  code/libraries/joomlatools/component/koowa/user/user.php
  code/libraries/joomlatools/library/user/abstract.php
  code/libraries/joomlatools/library/user/interface.php
Labels: feature, refactor
